//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSI2999_KnowledgeClicker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> numKnowledge { get; set; }
        public Nullable<int> totalKnowledge { get; set; }
        public Nullable<int> numBook { get; set; }
        public Nullable<int> numTutor { get; set; }
        public Nullable<int> numProf { get; set; }
        public Nullable<int> numSchool { get; set; }
        public Nullable<int> numUni { get; set; }
        public Nullable<int> numLab { get; set; }
        public Nullable<int> Level { get; set; }
    }
}
